### PR TITLE
Change dependency version number

### PR DESCRIPTION
**Pull request by snakecharmer**
Changed package & readme to use the middleware with the new Kitura

### CODE REVIEW

**Comment by shmuelk** [comment]
@snakecharmer Thanks for the PR that corrects my oversight when I migrated Kitura to the 07/25 drop of Swift 3.

Please complete a Contributor License Agreement (CLA). Please see our [CLA repo](http://github.com/IBM-Swift/CLA) for more information.

**Comment by shmuelk** [comment]
@snakecharmer As you are already getting this repo set for Swift 3 07/25, please add to it a .swift-version file. You copy the one in Kitura's repo. Make sure it points at the 07/25 version of Swift.

**Comment by shmuelk** [comment]
@snakecharmer Please change the dependency version to be of the form:

    majorVersion: 0, minor: 25

**Comment by snakecharmer** [comment]
@shmuelk CLA signed & sent and code modified as requested.

**Pull request merged**
